#!/bin/sh
#
# gitbucket - this script starts and stops the gitbucket daemon
#
# chkconfig:   - 85 15
# description:  GitBucket
# processname: gitbucket
# pidfile:     /var/run/gitbucket.pid

# Source function library.
. /etc/rc.d/init.d/functions

gitbucket="/root/start-gitbucket.sh"
prog=gitbucket

lockfile="/var/lock/subsys/gitbucket"
pidfile="/var/run/gitbucket.pid"

start() {
    [ -x $gitbucket ] || exit 5
    echo -n $"Starting $prog: "
    daemon $gitbucket
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_$1
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
